package com.zhangjun.mall;

import com.alibaba.fastjson2.JSON;
import com.zhangjun.mall.utils.JwtTokenUtil;
import io.jsonwebtoken.Claims;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.core.DefaultParameterNameDiscoverer;
import org.springframework.core.ParameterNameDiscoverer;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.web.util.UrlUtils;

@SpringBootTest(classes = MallAdminApplication.class)
class MallAdminApplicationTests {

	@Autowired
	JwtTokenUtil jwtTokenUtil;

	@Test
	void contextLoads() {


		String token="eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI1YTM1MTJmZjNlMGY0NGQ4YTA3NGExMjgzODhhOGE3MCIsInN1YiI6IntcImFjY291bnROb25FeHBpcmVkXCI6dHJ1ZSxcImFjY291bnROb25Mb2NrZWRcIjp0cnVlLFwiY3JlZGVudGlhbHNOb25FeHBpcmVkXCI6dHJ1ZSxcImVuYWJsZWRcIjp0cnVlLFwibGlzdFwiOlt7XCJjYXRlZ29yeUlkXCI6MSxcImNyZWF0ZVRpbWVcIjoxNTgwODA3MDk1MDAwLFwiaWRcIjoxLFwibmFtZVwiOlwi5ZWG5ZOB5ZOB54mM566h55CGXCIsXCJ1cmxcIjpcIi9icmFuZC8qKlwifSx7XCJjYXRlZ29yeUlkXCI6MSxcImNyZWF0ZVRpbWVcIjoxNTgwODA3MTM1MDAwLFwiaWRcIjoyLFwibmFtZVwiOlwi5ZWG5ZOB5bGe5oCn5YiG57G7566h55CGXCIsXCJ1cmxcIjpcIi9wcm9kdWN0QXR0cmlidXRlL2NhdGVnb3J5LyoqXCJ9LHtcImNhdGVnb3J5SWRcIjoxLFwiY3JlYXRlVGltZVwiOjE1ODA4MDcxNzMwMDAsXCJpZFwiOjMsXCJuYW1lXCI6XCLllYblk4HlsZ7mgKfnrqHnkIZcIixcInVybFwiOlwiL3Byb2R1Y3RBdHRyaWJ1dGUvKipcIn0se1wiY2F0ZWdvcnlJZFwiOjEsXCJjcmVhdGVUaW1lXCI6MTU4MDgwNzIzNTAwMCxcImlkXCI6NCxcIm5hbWVcIjpcIuWVhuWTgeWIhuexu-euoeeQhlwiLFwidXJsXCI6XCIvcHJvZHVjdENhdGVnb3J5LyoqXCJ9LHtcImNhdGVnb3J5SWRcIjoxLFwiY3JlYXRlVGltZVwiOjE1ODA4MDczNTYwMDAsXCJpZFwiOjUsXCJuYW1lXCI6XCLllYblk4HnrqHnkIZcIixcInVybFwiOlwiL3Byb2R1Y3QvKipcIn0se1wiY2F0ZWdvcnlJZFwiOjEsXCJjcmVhdGVUaW1lXCI6MTU4MDgwNzM5MzAwMCxcImlkXCI6NixcIm5hbWVcIjpcIuWVhuWTgeW6k-WtmOeuoeeQhlwiLFwidXJsXCI6XCIvc2t1LyoqXCJ9LHtcImNhdGVnb3J5SWRcIjoyLFwiY3JlYXRlVGltZVwiOjE1ODA4ODUwMTcwMDAsXCJkZXNjcmlwdGlvblwiOlwiXCIsXCJpZFwiOjgsXCJuYW1lXCI6XCLorqLljZXnrqHnkIZcIixcInVybFwiOlwiL29yZGVyLyoqXCJ9LHtcImNhdGVnb3J5SWRcIjoyLFwiY3JlYXRlVGltZVwiOjE1ODA4ODUwNjIwMDAsXCJkZXNjcmlwdGlvblwiOlwiXCIsXCJpZFwiOjksXCJuYW1lXCI6XCIg6K6i5Y2V6YCA6LSn55Sz6K-3566h55CGXCIsXCJ1cmxcIjpcIi9yZXR1cm5BcHBseS8qKlwifSx7XCJjYXRlZ29yeUlkXCI6MixcImNyZWF0ZVRpbWVcIjoxNTgwODg1MTA4MDAwLFwiZGVzY3JpcHRpb25cIjpcIlwiLFwiaWRcIjoxMCxcIm5hbWVcIjpcIumAgOi0p-WOn-WboOeuoeeQhlwiLFwidXJsXCI6XCIvcmV0dXJuUmVhc29uLyoqXCJ9LHtcImNhdGVnb3J5SWRcIjoyLFwiY3JlYXRlVGltZVwiOjE1ODA4ODUxNDMwMDAsXCJkZXNjcmlwdGlvblwiOlwiXCIsXCJpZFwiOjExLFwibmFtZVwiOlwi6K6i5Y2V6K6-572u566h55CGXCIsXCJ1cmxcIjpcIi9vcmRlclNldHRpbmcvKipcIn0se1wiY2F0ZWdvcnlJZFwiOjIsXCJjcmVhdGVUaW1lXCI6MTU4MDg4NTE4MzAwMCxcImRlc2NyaXB0aW9uXCI6XCJcIixcImlkXCI6MTIsXCJuYW1lXCI6XCLmlLbotKflnLDlnYDnrqHnkIZcIixcInVybFwiOlwiL2NvbXBhbnlBZGRyZXNzLyoqXCJ9LHtcImNhdGVnb3J5SWRcIjozLFwiY3JlYXRlVGltZVwiOjE1ODEwNjQ2NDIwMDAsXCJkZXNjcmlwdGlvblwiOlwiXCIsXCJpZFwiOjEzLFwibmFtZVwiOlwi5LyY5oOg5Yi4566h55CGXCIsXCJ1cmxcIjpcIi9jb3Vwb24vKipcIn0se1wiY2F0ZWdvcnlJZFwiOjMsXCJjcmVhdGVUaW1lXCI6MTU4MTA2NDY3OTAwMCxcImRlc2NyaXB0aW9uXCI6XCJcIixcImlkXCI6MTQsXCJuYW1lXCI6XCLkvJjmg6DliLjpooblj5borrDlvZXnrqHnkIZcIixcInVybFwiOlwiL2NvdXBvbkhpc3RvcnkvKipcIn0se1wiY2F0ZWdvcnlJZFwiOjMsXCJjcmVhdGVUaW1lXCI6MTU4MTA2NDcwODAwMCxcImRlc2NyaXB0aW9uXCI6XCJcIixcImlkXCI6MTUsXCJuYW1lXCI6XCLpmZDml7botK3mtLvliqjnrqHnkIZcIixcInVybFwiOlwiL2ZsYXNoLyoqXCJ9LHtcImNhdGVnb3J5SWRcIjozLFwiY3JlYXRlVGltZVwiOjE1ODEwNjQ3MzkwMDAsXCJkZXNjcmlwdGlvblwiOlwiXCIsXCJpZFwiOjE2LFwibmFtZVwiOlwi6ZmQ5pe26LSt5ZWG5ZOB5YWz57O7566h55CGXCIsXCJ1cmxcIjpcIi9mbGFzaFByb2R1Y3RSZWxhdGlvbi8qKlwifSx7XCJjYXRlZ29yeUlkXCI6MyxcImNyZWF0ZVRpbWVcIjoxNTgxMDY0NzYyMDAwLFwiZGVzY3JpcHRpb25cIjpcIlwiLFwiaWRcIjoxNyxcIm5hbWVcIjpcIumZkOaXtui0reWcuuasoeeuoeeQhlwiLFwidXJsXCI6XCIvZmxhc2hTZXNzaW9uLyoqXCJ9LHtcImNhdGVnb3J5SWRcIjozLFwiY3JlYXRlVGltZVwiOjE1ODEwNjQ4MDcwMDAsXCJkZXNjcmlwdGlvblwiOlwiXCIsXCJpZFwiOjE4LFwibmFtZVwiOlwi6aaW6aG16L2u5pKt5bm_5ZGK566h55CGXCIsXCJ1cmxcIjpcIi9ob21lL2FkdmVydGlzZS8qKlwifSx7XCJjYXRlZ29yeUlkXCI6MyxcImNyZWF0ZVRpbWVcIjoxNTgxMDY0ODM0MDAwLFwiZGVzY3JpcHRpb25cIjpcIlwiLFwiaWRcIjoxOSxcIm5hbWVcIjpcIummlumhteWTgeeJjOeuoeeQhlwiLFwidXJsXCI6XCIvaG9tZS9icmFuZC8qKlwifSx7XCJjYXRlZ29yeUlkXCI6MyxcImNyZWF0ZVRpbWVcIjoxNTgxMDY0ODY2MDAwLFwiZGVzY3JpcHRpb25cIjpcIlwiLFwiaWRcIjoyMCxcIm5hbWVcIjpcIummlumhteaWsOWTgeeuoeeQhlwiLFwidXJsXCI6XCIvaG9tZS9uZXdQcm9kdWN0LyoqXCJ9LHtcImNhdGVnb3J5SWRcIjozLFwiY3JlYXRlVGltZVwiOjE1ODEwNjQ5MzYwMDAsXCJkZXNjcmlwdGlvblwiOlwiXCIsXCJpZFwiOjIxLFwibmFtZVwiOlwi6aaW6aG15Lq65rCU5o6o6I2Q566h55CGXCIsXCJ1cmxcIjpcIi9ob21lL3JlY29tbWVuZFByb2R1Y3QvKipcIn0se1wiY2F0ZWdvcnlJZFwiOjMsXCJjcmVhdGVUaW1lXCI6MTU4MTA2NDk2ODAwMCxcImRlc2NyaXB0aW9uXCI6XCJcIixcImlkXCI6MjIsXCJuYW1lXCI6XCLpppbpobXkuJPpopjmjqjojZDnrqHnkIZcIixcInVybFwiOlwiL2hvbWUvcmVjb21tZW5kU3ViamVjdC8qKlwifSx7XCJjYXRlZ29yeUlkXCI6NSxcImNyZWF0ZVRpbWVcIjoxNTgxMDY1MDk2MDAwLFwiZGVzY3JpcHRpb25cIjpcIlwiLFwiaWRcIjoyMyxcIm5hbWVcIjpcIiDllYblk4HkvJjpgInnrqHnkIZcIixcInVybFwiOlwiL3ByZWZyZW5jZUFyZWEvKipcIn0se1wiY2F0ZWdvcnlJZFwiOjUsXCJjcmVhdGVUaW1lXCI6MTU4MTA2NTEzOTAwMCxcImRlc2NyaXB0aW9uXCI6XCJcIixcImlkXCI6MjQsXCJuYW1lXCI6XCLllYblk4HkuJPpopjnrqHnkIZcIixcInVybFwiOlwiL3N1YmplY3QvKipcIn0se1wiY2F0ZWdvcnlJZFwiOjQsXCJjcmVhdGVUaW1lXCI6MTU4MTA2NTI1NDAwMCxcImRlc2NyaXB0aW9uXCI6XCJcIixcImlkXCI6MjUsXCJuYW1lXCI6XCLlkI7lj7DnlKjmiLfnrqHnkIZcIixcInVybFwiOlwiL2FkbWluLyoqXCJ9LHtcImNhdGVnb3J5SWRcIjo0LFwiY3JlYXRlVGltZVwiOjE1ODEwNjUzMDQwMDAsXCJkZXNjcmlwdGlvblwiOlwiXCIsXCJpZFwiOjI2LFwibmFtZVwiOlwi5ZCO5Y-w55So5oi36KeS6Imy566h55CGXCIsXCJ1cmxcIjpcIi9yb2xlLyoqXCJ9LHtcImNhdGVnb3J5SWRcIjo0LFwiY3JlYXRlVGltZVwiOjE1ODEwNjUzMjgwMDAsXCJkZXNjcmlwdGlvblwiOlwiXCIsXCJpZFwiOjI3LFwibmFtZVwiOlwi5ZCO5Y-w6I-c5Y2V566h55CGXCIsXCJ1cmxcIjpcIi9tZW51LyoqXCJ9LHtcImNhdGVnb3J5SWRcIjo0LFwiY3JlYXRlVGltZVwiOjE1ODEwNjUzNTgwMDAsXCJkZXNjcmlwdGlvblwiOlwiXCIsXCJpZFwiOjI4LFwibmFtZVwiOlwi5ZCO5Y-w6LWE5rqQ5YiG57G7566h55CGXCIsXCJ1cmxcIjpcIi9yZXNvdXJjZUNhdGVnb3J5LyoqXCJ9LHtcImNhdGVnb3J5SWRcIjo0LFwiY3JlYXRlVGltZVwiOjE1ODEwNjUzODUwMDAsXCJkZXNjcmlwdGlvblwiOlwiXCIsXCJpZFwiOjI5LFwibmFtZVwiOlwi5ZCO5Y-w6LWE5rqQ566h55CGXCIsXCJ1cmxcIjpcIi9yZXNvdXJjZS8qKlwifSx7XCJjYXRlZ29yeUlkXCI6NyxcImNyZWF0ZVRpbWVcIjoxNjAwNTAxNjc3MDAwLFwiZGVzY3JpcHRpb25cIjpcIlwiLFwiaWRcIjozMCxcIm5hbWVcIjpcIuS8muWRmOetiee6p-euoeeQhlwiLFwidXJsXCI6XCIvbWVtYmVyTGV2ZWwvKipcIn1dLFwicGFzc3dvcmRcIjpcIiQyYSQxMCRMR21ULjdoWWxHVjhKdVo2NzFFTVZlcGJBMmlac1ZSQWJsemNUWm1qbHlhS216cGlZQmNvMlwiLFwidW1zQWRtaW5cIjp7XCJjcmVhdGVUaW1lXCI6MTUzODk3Njc2NzAwMCxcImVtYWlsXCI6XCJhZG1pbkAxNjMuY29tXCIsXCJpY29uXCI6XCJodHRwczovL21hY3JvLW9zcy5vc3MtY24tc2hlbnpoZW4uYWxpeXVuY3MuY29tL21hbGwvaWNvbi9naXRodWJfaWNvbl8wMS5wbmdcIixcImlkXCI6MyxcImxvZ2luVGltZVwiOjE1NTU3MzU1MTYwMDAsXCJuaWNrTmFtZVwiOlwi57O757uf566h55CG5ZGYXCIsXCJub3RlXCI6XCLns7vnu5_nrqHnkIblkZhcIixcInBhc3N3b3JkXCI6XCIkMmEkMTAkTEdtVC43aFlsR1Y4SnVaNjcxRU1WZXBiQTJpWnNWUkFibHpjVFptamx5YUttenBpWUJjbzJcIixcInN0YXR1c1wiOjEsXCJ1c2VybmFtZVwiOlwiYWRtaW5cIn0sXCJ1c2VybmFtZVwiOlwiYWRtaW5cIn0iLCJpc3MiOiJ6aGFuZ2p1biIsImlhdCI6MTc0NzQxNjA4MCwiZXhwIjoxNzQ4MDIwODgwfQ.MzHJ1hpsKVtfYMXHCsnxlpKQViWeAdK2IM8kV7aB3SY";

		boolean count = jwtTokenUtil.isTokenExpired(token);

		Claims claims =jwtTokenUtil.parseJWT(token);
		String subject = claims.getSubject();
		//把字符串转成loginUser对象
		UserDetails loginUser = JSON.parseObject(subject, UserDetails.class);

		jwtTokenUtil.validateToken(token,loginUser);

		ParameterNameDiscoverer discoverer = new DefaultParameterNameDiscoverer();

		//String[] paramNames = discoverer.getParameterNames(org.springframework.security.web.util.UrlUtils.buildRequestUrl(r.getServletPath(), r.getRequestURI(), r.getContextPath(), r.getPathInfo(),
		//		r.getQueryString());
	}

}
