spring:
  application:
    name: mall-admin
  profiles:
    active: dev
  mvc:
    path match:
      matching-strategy: ant_path_matcher

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

redis:
  database: mall
  key:
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
  expire: 86400 #24小时

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-ui/**
      - /webjars/**
      - /v3/api-docs/**
      - /admin/login

logging:
  level:
    org:
      springframework:
        security: DEBUG
    com:
      zhangjun:
        mall: TRACE
