spring:
  application:
    name: mall-portal
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

secure:
  ignored:
    urls: #访问白名单
      - /swagger-ui/**
      - /v3/api-docs/**
      - /swagger-ui.html
      - /webjars/**
      - /user/login


